[package]
name = "qctc"
version = "0.1.0"
authors = ["BOBO1997git <yh198595@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
